DROP TABLE CLIENTE;
DROP TABLE BICICLETA;
DROP TABLE GUIDAO;
DROP TABLE SELIM;
DROP TABLE QUADRO;
DROP TABLE RODAS;

CREATE TABLE CLIENTE(
    ID_CLIENTE INT,
    DT_NASCIMENTO DATE NOT NULL,
    E_MAIL VARCHAR(50) NOT NULL,
    NR_TELEFONE VARCHAR(11) NOT NULL,
    NM_NOME VARCHAR(60) NOT NULL,
    CEP INT NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    CONSTRAINT pk_id_cliente PRIMARY KEY (ID_CLIENTE)
    );

CREATE TABLE BICICLETA(
    MODELO_DA_BICICLETA VARCHAR(60),
    NOTA_FISCAL FLOAT,
    ID_CLIENTE INT,
    CONSTRAINT pk_modelo_da_bicicleta PRIMARY KEY (MODELO_DA_BICICLETA),
    CONSTRAINT Check_NOTA_FISCAL CHECK (NOTA_FISCAL <= 100000),
    CONSTRAINT fk_BICICLETA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
    ); 

CREATE TABLE GUIDAO(
    MARCA_GUIDAO VARCHAR(60),
    MANOPLAS VARCHAR(60),
    MANETE_DE_FREIO VARCHAR(60),
    ALAVANCA_DE_CAMBIO VARCHAR(60) NOT NULL,
    MODELO_DA_BICICLETA VARCHAR(60),
    CONSTRAINT pk_marca_guidao PRIMARY KEY (MARCA_GUIDAO),
    CONSTRAINT fk_GUIDAO_BICICLETA FOREIGN KEY (MODELO_DA_BICICLETA) REFERENCES BICICLETA(MODELO_DA_BICICLETA)
    );

CREATE TABLE SELIM(
    MARCA_SELIM VARCHAR(60),
    CANOTE VARCHAR(60),
    MESA VARCHAR(60),
    ABRACADEIRA VARCHAR(60),
    MODELO_DA_BICICLETA VARCHAR(60),
    CONSTRAINT pk_marca_selim PRIMARY KEY (MARCA_SELIM),
    CONSTRAINT fk_SELIM_BICICLETA FOREIGN KEY (MODELO_DA_BICICLETA) REFERENCES BICICLETA(MODELO_DA_BICICLETA)
    );
CREATE TABLE QUADRO(
    MARCA_QUADRO VARCHAR(60),
    PEDAL VARCHAR(60),
    PEDIVELA VARCHAR(60) NOT NULL,
    CAIXA_DE_DIRECAO VARCHAR(60),
    GARFO VARCHAR(60), 
    MODELO_DA_BICICLETA VARCHAR(60),
    CONSTRAINT pk_marca_quadro PRIMARY KEY (MARCA_QUADRO),
    CONSTRAINT fk_QUADRO_BICICLETA FOREIGN KEY (MODELO_DA_BICICLETA) REFERENCES BICICLETA(MODELO_DA_BICICLETA)
    ); 

CREATE TABLE RODAS(
    MARCA_RODAS VARCHAR(60),
    FREIO VARCHAR(60),
    CAMBIO_TRASEIRO VARCHAR(60) NOT NULL,
    CAMBIO_DIANTEIRO VARCHAR(60) NOT NULL,
    CASSETE VARCHAR(60) NOT NULL,
    CORRENTE VARCHAR(60),
    SUSPENSAO_TRASEIRA VARCHAR(60),
    MODELO_DA_BICICLETA VARCHAR(60),
    CONSTRAINT pk_marca_rodas PRIMARY KEY (MARCA_RODAS),
    CONSTRAINT fk_RODAS_BICICLETA FOREIGN KEY (MODELO_DA_BICICLETA) REFERENCES BICICLETA(MODELO_DA_BICICLETA)
    );


--?	Eduardo Finardi | RM: 98624
--?	Miguel Santos | RM: 551640
--?	Murilo Munari | RM: 94164
--?	Felipe Morais | RM: 551463
--?	Joao Cardoso | RM: 552078
